"""Master catalog of products and constants for WooCommerce simulation."""

from src.ingest.models import Product

PRODUCTS_CATALOG: list[Product] = [
    {
        "id": 101,
        "sku": "AFN-FIL-101",
        "name": "Filtro de Aceite Sintético Premium",
        "brand": "Fram",
        "category": "Filtración",
        "price": 250.0,
        "cost": 110.0,
    },
    {
        "id": 102,
        "sku": "AFN-BRA-102",
        "name": "Balatas Delanteras Cerámica de Alta Performance",
        "brand": "Brembo",
        "category": "Frenos",
        "price": 850.0,
        "cost": 390.0,
    },
    {
        "id": 103,
        "sku": "AFN-LUB-103",
        "name": "Aceite de Motor Sintético 5W-30 (1L)",
        "brand": "Mobil 1",
        "category": "Lubricantes",
        "price": 190.0,
        "cost": 85.0,
    },
    {
        "id": 104,
        "sku": "AFN-IGN-104",
        "name": "Bujía de Iridio de Larga Duración",
        "brand": "NGK",
        "category": "Encendido",
        "price": 160.0,
        "cost": 65.0,
    },
    {
        "id": 105,
        "sku": "AFN-BRA-105",
        "name": "Disco de Freno Ventilado Delantero",
        "brand": "Bosch",
        "category": "Frenos",
        "price": 1200.0,
        "cost": 550.0,
    },
    {
        "id": 106,
        "sku": "AFN-FIL-106",
        "name": "Filtro de Aire de Motor Premium",
        "brand": "Mann Filter",
        "category": "Filtración",
        "price": 320.0,
        "cost": 145.0,
    },
    {
        "id": 107,
        "sku": "AFN-FIL-107",
        "name": "Filtro de Cabina de Carbón Activo",
        "brand": "Bosch",
        "category": "Filtración",
        "price": 280.0,
        "cost": 120.0,
    },
    {
        "id": 108,
        "sku": "AFN-FIL-108",
        "name": "Filtro de Combustible en Línea",
        "brand": "Gonher",
        "category": "Filtración",
        "price": 180.0,
        "cost": 75.0,
    },
    {
        "id": 109,
        "sku": "AFN-FIL-109",
        "name": "Filtro de Transmisión Automática",
        "brand": "ACDelco",
        "category": "Filtración",
        "price": 450.0,
        "cost": 210.0,
    },
    {
        "id": 110,
        "sku": "AFN-LUB-110",
        "name": "Aceite de Motor Mineral 20W-50 (946ml)",
        "brand": "Castrol",
        "category": "Lubricantes",
        "price": 140.0,
        "cost": 60.0,
    },
    {
        "id": 111,
        "sku": "AFN-LUB-111",
        "name": "Fluido de Transmisión Automática ATF Dexron VI",
        "brand": "Valvoline",
        "category": "Lubricantes",
        "price": 230.0,
        "cost": 105.0,
    },
    {
        "id": 112,
        "sku": "AFN-LUB-112",
        "name": "Líquido de Frenos DOT 4 de Alta Temperatura",
        "brand": "Wagner",
        "category": "Lubricantes",
        "price": 175.0,
        "cost": 78.0,
    },
    {
        "id": 113,
        "sku": "AFN-LUB-113",
        "name": "Grasa para Baleros y Chasis Multipropósito",
        "brand": "Bardahl",
        "category": "Lubricantes",
        "price": 95.0,
        "cost": 40.0,
    },
    {
        "id": 114,
        "sku": "AFN-BRA-114",
        "name": "Balatas Traseras de Tambor Específicas",
        "brand": "Fritec",
        "category": "Frenos",
        "price": 420.0,
        "cost": 190.0,
    },
    {
        "id": 115,
        "sku": "AFN-BRA-115",
        "name": "Cilindro de Rueda Trasera Hidráulico",
        "brand": "Dorman",
        "category": "Frenos",
        "price": 310.0,
        "cost": 135.0,
    },
    {
        "id": 116,
        "sku": "AFN-BRA-116",
        "name": "Manguera de Freno Delantera Reforzada",
        "brand": "Brake Premium",
        "category": "Frenos",
        "price": 260.0,
        "cost": 115.0,
    },
    {
        "id": 117,
        "sku": "AFN-IGN-117",
        "name": "Bujía de Platino G-Power",
        "brand": "NGK",
        "category": "Encendido",
        "price": 95.0,
        "cost": 38.0,
    },
    {
        "id": 118,
        "sku": "AFN-IGN-118",
        "name": "Juego de Cables para Bujías 8mm",
        "brand": "Kem",
        "category": "Encendido",
        "price": 580.0,
        "cost": 260.0,
    },
    {
        "id": 119,
        "sku": "AFN-IGN-119",
        "name": "Bobina de Encendido Tipo Bloque",
        "brand": "Delphi",
        "category": "Encendido",
        "price": 920.0,
        "cost": 420.0,
    },
    {
        "id": 120,
        "sku": "AFN-IGN-120",
        "name": "Rotor de Distribuidor Eléctrico",
        "brand": "Standard",
        "category": "Encendido",
        "price": 115.0,
        "cost": 48.0,
    },
    {
        "id": 121,
        "sku": "AFN-SUS-121",
        "name": "Amortiguador Delantero de Gas Presurizado",
        "brand": "KYB",
        "category": "Suspensión y Dirección",
        "price": 1450.0,
        "cost": 680.0,
    },
    {
        "id": 122,
        "sku": "AFN-SUS-122",
        "name": "Terminal de Dirección Externa Lado Derecho",
        "brand": "SYD",
        "category": "Suspensión y Dirección",
        "price": 340.0,
        "cost": 150.0,
    },
    {
        "id": 123,
        "sku": "AFN-SUS-123",
        "name": "Rotula de Suspensión Delantera Inferior",
        "brand": "Moog",
        "category": "Suspensión y Dirección",
        "price": 490.0,
        "cost": 220.0,
    },
    {
        "id": 124,
        "sku": "AFN-SUS-124",
        "name": "Buje de Horquilla Inferior Reforzado",
        "brand": "Dai",
        "category": "Suspensión y Dirección",
        "price": 120.0,
        "cost": 50.0,
    },
    {
        "id": 125,
        "sku": "AFN-SUS-125",
        "name": "Tornillo Estabilizador Delantero (Cacahuate)",
        "brand": "GroB",
        "category": "Suspensión y Dirección",
        "price": 210.0,
        "cost": 90.0,
    },
    {
        "id": 126,
        "sku": "AFN-ELC-126",
        "name": "Batería Coche 12V 600 Amp",
        "brand": "LTH",
        "category": "Sistema Eléctrico",
        "price": 2400.0,
        "cost": 1150.0,
    },
    {
        "id": 127,
        "sku": "AFN-ELC-127",
        "name": "Alternador de Motor Reconstruido 90 Amp",
        "brand": "Valeo",
        "category": "Sistema Eléctrico",
        "price": 3100.0,
        "cost": 1400.0,
    },
    {
        "id": 128,
        "sku": "AFN-ELC-128",
        "name": "Foco Halógeno H4 High/Low Beam",
        "brand": "Hella",
        "category": "Sistema Eléctrico",
        "price": 135.0,
        "cost": 55.0,
    },
    {
        "id": 129,
        "sku": "AFN-ELC-129",
        "name": "Marcha Motor de Arranque Eléctrico",
        "brand": "Denso",
        "category": "Sistema Eléctrico",
        "price": 1850.0,
        "cost": 890.0,
    },
    {
        "id": 130,
        "sku": "AFN-COO-130",
        "name": "Anticongelante Concentrado 50/50 Rojo",
        "brand": "Prestone",
        "category": "Enfriamiento",
        "price": 299.0,
        "cost": 135.0,
    },
    {
        "id": 131,
        "sku": "AFN-COO-131",
        "name": "Bomba de Agua para Motor de Aluminio",
        "brand": "Gates",
        "category": "Enfriamiento",
        "price": 780.0,
        "cost": 340.0,
    },
    {
        "id": 132,
        "sku": "AFN-COO-132",
        "name": "Termostato de Motor Grados Originales",
        "brand": "Stant",
        "category": "Enfriamiento",
        "price": 240.0,
        "cost": 100.0,
    },
    {
        "id": 133,
        "sku": "AFN-COO-133",
        "name": "Radiador de Motor Aluminio-Plástico",
        "brand": "Dei",
        "category": "Enfriamiento",
        "price": 1650.0,
        "cost": 780.0,
    },
    {
        "id": 134,
        "sku": "AFN-COO-134",
        "name": "Tapón de Radiador 16 Libras de Presión",
        "brand": "MotoRad",
        "category": "Enfriamiento",
        "price": 90.0,
        "cost": 35.0,
    },
    {
        "id": 135,
        "sku": "AFN-MOT-135",
        "name": "Banda de Distribución Dentada (Timing Belt)",
        "brand": "Gates",
        "category": "Motor",
        "price": 480.0,
        "cost": 210.0,
    },
    {
        "id": 136,
        "sku": "AFN-MOT-136",
        "name": "Empaque de Tapa de Punterías Siliconado",
        "brand": "TF Victor",
        "category": "Motor",
        "price": 220.0,
        "cost": 95.0,
    },
    {
        "id": 137,
        "sku": "AFN-MOT-137",
        "name": "Soporte de Motor Frontal Derecho",
        "brand": "Eagle BHP",
        "category": "Motor",
        "price": 680.0,
        "cost": 310.0,
    },
    {
        "id": 138,
        "sku": "AFN-MOT-138",
        "name": "Puntería Hidráulica (Buzo de Motor)",
        "brand": "Moresa",
        "category": "Motor",
        "price": 145.0,
        "cost": 60.0,
    },
    {
        "id": 139,
        "sku": "AFN-MOT-139",
        "name": "Juego de Anillos para Pistón Estándar",
        "brand": "Perfect Circle",
        "category": "Motor",
        "price": 980.0,
        "cost": 460.0,
    },
    {
        "id": 140,
        "sku": "AFN-ACC-140",
        "name": "Pluma Limpiaparabrisas 22 Pulgadas Premium",
        "brand": "Bosch AeroTwin",
        "category": "Accesorios y Detallado",
        "price": 290.0,
        "cost": 125.0,
    },
    {
        "id": 141,
        "sku": "AFN-ACC-141",
        "name": "Limpia Parabrisas Concentrado Líquido (1L)",
        "brand": "Sonax",
        "category": "Accesorios y Detallado",
        "price": 120.0,
        "cost": 50.0,
    },
    {
        "id": 142,
        "sku": "AFN-ACC-142",
        "name": "Shampoo para Carrocería con Cera Carnauba",
        "brand": "Meguiar's",
        "category": "Accesorios y Detallado",
        "price": 340.0,
        "cost": 160.0,
    },
    {
        "id": 143,
        "sku": "AFN-ACC-143",
        "name": "Cera Líquida Protectora de Alta Pintura",
        "brand": "Turtle Wax",
        "category": "Accesorios y Detallado",
        "price": 210.0,
        "cost": 95.0,
    },
    {
        "id": 144,
        "sku": "AFN-FUE-144",
        "name": "Inyector de Combustible Multipunto Específico",
        "brand": "Tomco",
        "category": "Combustible",
        "price": 890.0,
        "cost": 410.0,
    },
    {
        "id": 145,
        "sku": "AFN-FUE-145",
        "name": "Repuesto de Bomba de Gasolina Eléctrica",
        "brand": "Walbro",
        "category": "Combustible",
        "price": 670.0,
        "cost": 290.0,
    },
    {
        "id": 146,
        "sku": "AFN-FUE-146",
        "name": "Regulador de Presión de Combustible Inyección",
        "brand": "Kem",
        "category": "Combustible",
        "price": 540.0,
        "cost": 240.0,
    },
    {
        "id": 147,
        "sku": "AFN-TRA-147",
        "name": "Kit de Embrague (Clutch) Completo Disco/Plato",
        "brand": "Luk",
        "category": "Transmisión",
        "price": 2850.0,
        "cost": 1350.0,
    },
    {
        "id": 148,
        "sku": "AFN-TRA-148",
        "name": "Junta Homocinética Lado Rueda con Cubrepolvo",
        "brand": "Race",
        "category": "Transmisión",
        "price": 720.0,
        "cost": 320.0,
    },
    {
        "id": 149,
        "sku": "AFN-TRA-149",
        "name": "Cubrepolvo de Dirección Tipo Acordeón Universal",
        "brand": "Dai",
        "category": "Transmisión",
        "price": 85.0,
        "cost": 32.0,
    },
    {
        "id": 150,
        "sku": "AFN-TRA-150",
        "name": "Balero Maza de Rueda Delantera con Abs",
        "brand": "SKF",
        "category": "Transmisión",
        "price": 1350.0,
        "cost": 610.0,
    },
]

METHODS_PAYMENT: list[str] = [
    # Cards
    "credit_card",
    "paypal",
    # Digital Wallets
    "apple_pay",
    "google_pay",
    "mercado_pago",
    # Cash and Retail
    "oxxo_pay",
    # Transfers
    "bank_transfer",
    "cod",
    # BNPL
    "kueski_pay",
]

ORDER_STATUS_CONFIG: dict[str, list] = {
    "statuses": ["completed", "processing", "failed", "cancelled"],
    "weights": [
        0.70,
        0.15,
        0.10,
        0.05,
    ],  # 70% exito, 15% proceso, 10% fallo, 5% cancelado
}
